### ISSUE TITLE
[Bug]  _metadata rename into Metadata

### ISSUE THREAD

**Issue by redxeagle** [elastic/ecs-dotnet#104]
Hi,

currently, we play around with the usage of the schema. We have trouble with the metadata field. 

Is there any reason why the Metadata field is named _metadata?
Because also Elasticsearch mentioned here: "Field names beginning with _ are not supported"

There is another feature request to allow structured data on the root level. This would also be a solution. But we need a way to extend the logging with our own fields for business requirements. The schema does not fit here for all cases (e.g. we want to have all headers of the request logged)

**Comment by RowlandBanks** [comment]
I've also suffered from the same behaviour. One easy workaround is to add an [ingestion pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/pipeline.html) with a [rename processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/rename-processor.html) to rename the `_metadata` field to something without an underscore (we used `app` for example).

First, create a new pipeline with the rename processor:

```
// Create a pipeline to rename the _metadata field to app (fields starting with an underscore cannot be indexed by Elastic)
// We ignore failures because a failure to rename will be very obvious - there will be no app field.
PUT /_ingest/pipeline/application_pipeline
{
  "description": "",
  "processors": [
	{
	  "rename": {
		"field": "_metadata",
		"target_field": "app",
		"ignore_failure": true,
		"tag": "Rename _metadata to app"
	  }
	}
  ]
}
```

Then, when creating your index, give it a [default_pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html), for example:

```
PUT /application-000001
{
  "settings": {
    "default_pipeline": "application_pipeline"
  },
  "aliases": {
    "application-write":{
      "is_write_index": true 
    }
  }
}
```

**Comment by RascoApps** [comment]
Is this related to a schema change, why is it incorrect?

**Comment by RowlandBanks** [comment]
@RascoApps the problem with `_metadata` is that Elastic won't index fields starting with an underscore.

So all the application specific bits of logging one is are doing aren't being indexed by Elastic, so you can't search or filter on them.

I don't think there's a schema change that has caused this - it seems to have been the behaviour for a long time.

**Comment by kwsorensen** [comment]
I made a pull request to changed _metadata to metadata.

**Comment by RascoApps** [comment]
Maybe it should be changed to _meta?
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html

Scott Gross
972-757-5797
________________________________

**Comment by RowlandBanks** [comment]
> Maybe it should be changed to _meta?

@RascoApps The problem with `_meta` is it still starts with an underscore, so will suffer from the same "Elastic won't index it" problem.

I like `metadata` as a solution - ideally as a configurable default.

**Comment by yorondevops** [comment]
Hi, commenting here to see if it's possible to get the ball moving on this issue. 

I'm using the NLog ECS Layout and want to serialize key-value pairs from the MDLC as top-level fields into my log messages.

Looks like I'm running into the same issue as everyone else here where the ECS Layout prepends `_metadata` to the field names in the messages, making them unindexable.

Does anyone know a way to get around this problem?

**Comment by jstevensgithub** [comment]
Are you still going to implement this?  

I am using the NLog component and noticed "_metadata" gets ignored in the most recent version of Elastic.

I created a subclass for EcsLayout which will rename "_metadata" to "metadata" upon serialization.  However, I don't want to conflict with any planned future use-case for the "metadata" node.

If so, I can use just "data" that aligns with the Azure Event Grid schema for custom data.

**Comment by russcam** [comment]
This has been addressed in #138 by renaming `_metadata` to `metadata`.

What would be most useful to folks:

1. Release a new 1.5.x version now that includes this fix
2. Wait on a 1.6.x version that updates to ECS 1.6 and includes this fix. This requires some changes in the generator to accommodate changes in the ECS schema and will take a bit more time than a 1.5.x release.

Please vote on this comment with a  👍 for 1 and a ❤️ for 2.

Renaming the output of a field fixes the issue, but could be a breaking change for folks that might be expecting the `_metadata` field to be present

**Comment by russcam** [comment]
Thanks for voting! I will release a new 1.5.x version shortly, followed by a 1.6.x version

**Comment by russcam** [comment]
[1.5.3 has now been released to Nuget](https://github.com/elastic/ecs-dotnet/releases/tag/1.5.3).

Thank you for your patience!
