### ISSUE TITLE
[BUG] HttpContext.Request.Method is empty

### ISSUE THREAD

**Issue by Dujma** [elastic/ecs-dotnet#105]
**ECS schema version (e.g. 1.4.0)**: 1.5

**ECS .NET assembly version (e.g. 1.4.2)**: 1.5.1

**Elasticsearch version (if applicable)**:

**.NET framework / OS**: .NET Core 2.1 / Windows

**Description of the problem, including expected versus actual behavior**: The library seems to cause HttpContext.Request.Method to be empty in some random occurrences. This is most likely caused by HttpContext being accessed between the requests.

Additional resources:
 - https://github.com/dotnet/aspnetcore/issues/3627
 - https://github.com/aspnet/KestrelHttpServer/issues/2591

**Steps to reproduce**:
 1. Configure the ".MapHttpContext(ctx.Configuration.Get<HttpContextAccessor>())"
 2. Set up a script that will send 100+ requests to the service. Some of them should be 404 since the HttpContext.Request.Method isn't set.
 3. Remove the ".MapHttpContext(ctx.Configuration.Get<HttpContextAccessor>())"
 4. Set up a script that will send 100+ requests to the service. All requests should be fine.

**Comment by Dujma** [comment]
Upon further investigation, it seems that my service isn't handling the HTTP calls in the background and that the library is only reflecting that. I'll close this since I'm quite sure that the source of the problem is on my side. Thank you.

**Comment by Dujma** [comment]
Well, after a more extensive investigation, I'm quite sure that this one needs to be reopened. Indeed there was some issue with HTTP handling on my side that I've resolved, but still, the random 404 responses with empty "HttpContext.Request.Method" occur when mapping the Http Context is set in the configuration.

I believe the easiest way to debug this one would be to have an endpoint on the controller that would also send a request to some other endpoint outside the service. That is the pattern that I'm seeing in my service. When I'm receiving data on my endpoint, I'm performing a validation with other services.

Can someone please take a look at this one? Thanks.

**Comment by sgryphon** [comment]
@Dujma which library / package is having this issue - Extensions / NLog / Serilog / base ECS / other ?

Maybe also a small sample bit of code that demonstrates the issue would be useful.

**Comment by Dujma** [comment]
> @Dujma which library / package is having this issue - Extensions / NLog / Serilog / base ECS / other ?
> 
> 
> 
> Maybe also a small sample bit of code that demonstrates the issue would be useful.

Sorry for lack of info. It was with Serilog. Since then I've changed the code quite bit. But interesting part was that when I would include http logging, the random empty http method would be received by my controllers. If I would exclude the http logging, it would be fine. 

Not sure if this was some weird combination of my code and this lib, but it was causing problems for me.

If you are not able to reproduce it, it could be that this was a case of some weird combination of different implementations.

As said, the pattern that I've noticed is that this was happening on endpoints that were sending another request. For example on my endpoints, I had to verify the data from POST request with another service before returning appropriate status code.

**Comment by russcam** [comment]
@Dujma do you have a small example that reproduces the issue, that you can share?

**Comment by Dujma** [comment]
It's been quite some time. Since this I've updated my solution to 3.1 Net Core and used custom implementation.

What I can remember is that it was caused mostly in chained http contexts. For example, I would receive a request and send a new one while the original awaits. I've actually changed that to be asynchronous with messages bus. With that, it seem fine.

If you can't reproduce it, I would suggest resolving this one. It's tricky to reproduce it since it would happen randomly on some requests. Most of them would be fine.

Hope this helps a bit.

**Comment by russcam** [comment]
Thanks for the reply @Dujma. It does sound very similar to  dotnet/aspnetcore#3627 and aspnet/KestrelHttpServer#2591, but I think without a repro, it's going to be tricky to investigate.

I'm going to close this issue for now, but if it surfaces again and there's a way to repro it, please feel free to reopen 👍
