### ISSUE TITLE
This returned null for me and I got a null pointer exception when frame is used further down in the code

### ISSUE THREAD

**Issue by vrabac74** [elastic/ecs-dotnet#118]
https://github.com/elastic/ecs-dotnet/blob/9773308ef0743b86010e058b18f8f5a0a70cc5b1/src/Elastic.CommonSchema.Serilog/LogEventConverter.cs#L333

**Comment by snakefoot** [comment]
Duplicate of #102 ?

**Comment by vrabac74** [comment]
Ah yes sorry about that.
