### ISSUE TITLE
Update bug template to include the library (Extensions, Serilog, NLog, etc)

### ISSUE THREAD

**Issue by sgryphon** [elastic/ecs-dotnet#128]
**Is your feature request related to a problem? Please describe.**

Bug reports that say "X isn't working", but don't specify which library / logging platform they are using, are confusing. If the context is not clear, you need to first ask which library they are using.

**Describe the solution you'd like**

Update the bug template to include a question for which library/Nuget package the issue is related to (Extensions, Serilog, NLog, etc).

You could also add something similar in the feature request section, if relevant.

**Describe alternatives you've considered**

Having to either guess or ask in each submitted issue what it relates to.

**Additional context**

Could also add tags to make it easy to identify on the issue list. e.g. Core, Extensions, NLog, Serilog.

**Comment by russcam** [comment]
Closed in d64e2fd57c8dd3b4ee193d283aee7ef5a2460673
