### ISSUE TITLE
Tracing properties do not seem to match ecs

### ISSUE THREAD

**Issue by gregkalapos** [elastic/ecs-dotnet#13]
I think [the generated classes and properties](https://github.com/elastic/ecs-dotnet/blob/master/src/Elastic.CommonSchema/Types.Generated.cs#L3297) to store trace and transaction id do not match ecs.

What we generate here are:
- `tracing.trace.id`
- `tracing.transaction.id`

But they should be:
- `trace.id`
- `transaction.id`

See in [docs](https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html#_tracing_field_details) - I'm a little bit confused about this syntax, but e.g. the generated [go code](https://github.com/elastic/ecs/blob/master/code/go/ecs/tracing.go) does not seem to have the additional nesting we have here (`tracing`).

I tested with passing `EcsTextFormatter` to `serilog-sinks-elasticsearch`.

The test was done with #12.

All works fine, logs show up in Kibana. 

Problem is that the trace id is stored in `tracing.trace.id`, so the "View in APM" button does not work. - I assume it needs a `trace.id` field.

<img width="878" alt="Screen Shot 2019-12-10 at 17 15 20" src="https://user-images.githubusercontent.com/1091853/70547171-bf6b7880-1b70-11ea-8e07-6b900bb87de1.png">

Another reason I think the additional nesting is not needed is because Kibana searches for `trace.id` and not `transaction.trace.id` when you jump from a trace to logs - the query itself works, because of the `OR` you see in the statement, so that makes the "APM -> Log" jumping work, but for the other way I guess we need `trace.id`.

<img width="1695" alt="Screen Shot 2019-12-10 at 17 18 13" src="https://user-images.githubusercontent.com/1091853/70547419-1f621f00-1b71-11ea-87e9-e3ae642a9ea3.png">

**Comment by codebrain** [comment]
OK, this looks like a limitation in the generator, but one could argue that it is also a quirk in the ECS schema definition.

The `tracing` root object is described with a `prefix: ''`, the same as the `base` root object - on inspection these are the only two root objects defined with an empty string prefix.

https://github.com/elastic/ecs-dotnet/blob/5ffefce6519e03fac40bf56ab0d7ac473ffaed03/src/Specification/1.2/Core/ecs_nested.yml#L4639

I think it might make more sense for the schema to represent the `trace` and `transaction` object as either child objects on the `base` root, or to flatten the hierarchy by one level and have both `trace` and `transaction` exist as their own root objects. This would at least ensure that the schema is more consistent with itself.

In the meantime I will modify the generator to treat this object as described in the documentation and will raise an issue on the ecs repo.

**Comment by webmat** [comment]
Ah yeah for simplicity's sake both IDs were added in the same file "tracing", but their key names should actually be "trace.id" and "transaction.id".

Relying on the key [flat_name](https://github.com/elastic/ecs/blob/master/generated/ecs/ecs_nested.yml#L5266) in either the nested or flat representation of ECS yaml files will get you the correct key names for fields (base fields are also quirky that way).

You should not rely on the nesting to construct the key name. Leave that mess to me :-)

Corollary, if you need more precomputed values in either yaml file, please let me know. I'll be happy to add them to the ECS generator :-)
