### ISSUE TITLE
[FEATURE] Update to Elastic Common Schema 1.7

### ISSUE THREAD

**Issue by sgryphon** [elastic/ecs-dotnet#130]
Core minimum for release 1.7.0
* Autogenerate from the schema definition.
* Fix up any compatibility issues with clients/usage, e.g. different loggers.

Depending on the extent of changes, for anything new can either be added as part of the main release, or added as subsequent point releases.
* Review schema changes/additions for anything new that is worth adding to Extensions
* Review schema changes/additions for anything new that is worth adding to NLog
* Review schema changes/additions for anything new that is worth adding to Serilog
* Review schema changes/additions for anything new that is worth adding to other libraries

These don't all have to be done at once, or as a block, i.e. can incrementally add to different libraries as time permits.

Note that a lot of new fields may not be relevant for libraries, e.g. the new threat.technique.subtechnique field2 may have no directly relevant default values (like many other fields).

**Comment by Mpdreamz** [comment]
Closing this as `main` is now tracking `8.4.0`.
