### ISSUE TITLE
ECSTextFormatter to work with 'serilog-settings-configuration'

### ISSUE THREAD

**Issue by ekwebster** [elastic/ecs-dotnet#131]
https://github.com/serilog/serilog-settings-configuration

First time post, excuse me if I am not conforming to a format.

I want to use ECSTextFormatter, however I have am loading configuration of Serilog through the appettings.json. Is there any chance of this happening or a way to do this that I am just not seeing/understanding in the documentation?

Thank you in advance.

**Comment by russcam** [comment]
Hey @ekwebster, this is more a Serilog Settings Configuration question 🙂 It looks like you can do

```json
{
  "Serilog": {
    "Using": ["Serilog.Sinks.File"],
    "MinimumLevel": "Debug",
    "WriteTo": [{
        "Name": "Console"
      },
      {
        "Name": "File",
        "Args": {
          "formatter": "Elastic.CommonSchema.Serilog.EcsTextFormatter, Elastic.CommonSchema.Serilog",
          "path": "Logs/log.txt"
        }
      }
    ],
    "Properties": {
      "Application": "Sample"
    }
  }
}
```

With `Elastic.CommonSchema.Serilog` nuget package referenced by your application.

**Comment by russcam** [comment]
Closing issue as I believe the question is answered
