### ISSUE TITLE
[BUG] Using Elastic.CommonSchema.User, but still showing under _metadata

### ISSUE THREAD

**Issue by sgtobin** [elastic/ecs-dotnet#133]
This c# code...
```c#
class Program
{
    static void Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.Console(new EcsTextFormatter())
            .CreateLogger();
        var user = new Elastic.CommonSchema.User
        {
            Id = "111",
            Name = "test"
        };
        Log.Information("{@user}", user);
    }
}
```
...puts the `user` object under '_metadata'. I would have thought that because I used an `Elastic.CommonSchema.User` object, it would have come out at the top level. What am I missing?

Configuration...
Elastic.CommonSchema 1.5.1
Elastic.CommonSchema.Serilog 1.5.1
Serilog 2.10.0
Serilog.Sinks.Console 3.1.1
.net core 3.1 console application.

**Comment by russcam** [comment]
Hi @sgtobin, 

The Serilog message template and log event properties are put into `_metadata` as they don't map to ECS fields.

The `EcsTextFormatter` sets the  `User` top level property on the ECS `Base` type from the User property on a Http request:

https://github.com/elastic/ecs-dotnet/blob/b7d3fd1ed882c52c44d8f2421209d03ad1ec12c5/src/Elastic.CommonSchema.Serilog/LogEventConverter.cs#L73

The User property of the Http request represents the end user making the request, and comes from the Http context. For a console application, there isn't an equivalent to Http context that I'm aware of- there's the `Thread.CurrentPrincipal`, which might be set to the principal of a user initiating the action, which could be mapped with `.MapCustom(...)` on `EcsTextFormatterConfiguration` passed to `EcsTextFormatter`. Would you mind explaining a bit more about what you'd like to achieve?

**Comment by sgtobin** [comment]
@russcam, my bad. I guess I presumed too much. I thought I could use the package to easily construct json output that was an amalgamation of standard objects. 
```json
{
  "user": { 
    "id": "10",
    "full_name": "my name"
  },
  "error":{
     "id": "233",
     "message": "boom"
  }
}
```

**Comment by russcam** [comment]
Understood. Elastic.CommonSchema.Serilog is designed to format Serilog's `LogEvent` type to the Elastic Common Schema. Properties of `LogEvent` that don't map directly are placed into `_metadata`. 

I think you'd be able to achieve what you're after with Enrichers and `MapCustom(...)`; The enrichers  would enrich log events with properties about a user and os, then `MapCustom(...)` would be able to extract these values from `LogEvent` and map them to the ECS event.

**Comment by russcam** [comment]
For example, using `Serilog.Enrichers.Environment`

```c#
void Main()
{
	var configuration = new EcsTextFormatterConfiguration();
	configuration.MapCustom((ecs, logEvent) => {
		if (logEvent.Properties.TryGetValue("EnvironmentUserName", out var propertyValue) && propertyValue is ScalarValue s)
		{
			ecs.User = new Elastic.CommonSchema.User
			{
				Name = s.Value.ToString()
			};
		}
		
		return ecs;
	});
	
	var formatter = new EcsTextFormatter(configuration);

	Log.Logger = new LoggerConfiguration()
	.MinimumLevel.Debug()
	.Enrich.WithMachineName()
	.Enrich.WithEnvironmentUserName()
	.WriteTo.Console(formatter)
	.CreateLogger();
	
	var user = new Elastic.CommonSchema.User
	{
		Id = "111",
		Name = "test"
	};
	
	Log.Information("{@user}", user);
}
```

emits

```json
{
  "@timestamp": "2021-02-10T11:46:49.7178248+10:00",
  "log.level": "Information",
  "message": "User { Group: null, Id: \"111\", Name: \"test\", FullName: null, Email: null, Hash: null, Domain: null }",
  "_metadata": {
    "message_template": "{@user}",
    "user": {
      "group": null,
      "id": "111",
      "name": "test",
      "full_name": null,
      "email": null,
      "hash": null,
      "domain": null,
      "$type": "User"
    }
  },
  "ecs": {
    "version": "1.5.0"
  },
  "event": {
    "severity": 2,
    "timezone": "E. Australia Standard Time",
    "created": "2021-02-10T11:46:49.7178248+10:00"
  },
  "host": {
    "name": "XTREME"
  },
  "log": {
    "logger": "Elastic.CommonSchema.Serilog",
    "original": null
  },
  "process": {
    "thread": {
      "id": 1
    },
    "pid": 17616,
    "name": "LINQPad6.Query",
    "executable": "LINQPad6.Query"
  },
  "user": {
    "name": "XTREME\\russc"
  }
}
```

**Comment by sgtobin** [comment]
@russcam, thx. Here is what I ended up with...
```c#
var tfc = new EcsTextFormatterConfiguration();
tfc.MapCustom((ecsLogEvent, logEvent) =>
{
    var className = nameof(Elastic.CommonSchema.User);
    if (logEvent.Properties.TryGetValue(className.ToLower(), out var propertyValue))
    {
        var json = new StringWriter();
        new JsonValueFormatter().Format(propertyValue, json);
        ecsLogEvent.User = JsonConvert.DeserializeObject<Elastic.CommonSchema.User>(json.ToString());
    }
    return ecsLogEvent;
});
```  
Feels a little kludgy (especially the `className.ToLower()` bit) but works. Thx again.
