### ISSUE TITLE
[FEATURE] Enrich APM integrations with APM Service name

### ISSUE THREAD

**Issue by russcam** [elastic/ecs-dotnet#134]
The [ecs-logging spec defines a `service.name` property](https://github.com/elastic/ecs-logging/blob/503eb74bbb575712375c4c705cae9cf004beac21/spec/spec.json#L66-L74) that can be populated with the APM agent service name. ECS .NET APM integrations should populate this value.

### Possible Implementation

The APM .NET agent does not currently expose the Service name of the [agent instance on the `Agent` static class](https://github.com/russcam/apm-agent-dotnet/blob/f89b43eb30d53197ca004dc54c3ce2feb39ac140/src/Elastic.Apm/Agent.cs#L147). First, we should decide what should be exposed, and how to expose it. For example, it may not make sense to expose the whole `Service`, but just the name.

**Comment by alfkonee** [comment]
Hello @russcam Please isn't the Agent.Config Object containing the ServiceName. I think we could use `Agent.Config.ServiceName` to get the Service name if I'm missing something here please lemme know

**Comment by russcam** [comment]
@alfkonee yes, you are right. And since the discovered name is part of `ParseServiceName(...)`, in case a service name is not explicitly set, then using `Agent.Config.ServiceName` would be the easiest way to get it

**Comment by alfkonee** [comment]
@russcam In that case which field key do we enrich the logs with to add this linking is it just `service.name` cus it thats it's I could create a PR for the Serilog Enrichment (Maybe NLog too[Not very Familiar])

**Comment by odin568** [comment]
Coming from Java to .NET, stumbled about this issue as well. I miss a way to set the service.name, service.version and service.environment . Any way to accomplish? Using NLog

**Comment by NicolasREY69330** [comment]
Hello @russcam is it related to the fact we can't see Service Name in APM ? https://discuss.elastic.co/t/apm-net-agent-see-the-service-name-in-the-logs-for-correlated-transactions/311137
If yes is there a workaround ?
Thank you for your help

**Comment by Mpdreamz** [comment]
Just posting this here as well if you are using `EcsTextFormatter` with Serilog today you could use:

```
var config = new EcsTextFormatterConfiguration()
	.MapCustom((ecsDoc, log) =>
	{
		ecsDoc.Service = new Service { Name = Agent.Config.ServiceName };
		return ecsDoc;
	});
var formatter = new EcsTextFormatter(config);
```

We will make sure this works OOTB in the next update though.

**Comment by Mpdreamz** [comment]
https://github.com/elastic/ecs-dotnet/pull/209 should address this now.
