### ISSUE TITLE
[FEATURE] Option for omitting `_metadata` from fields serialized from the MDLC in Elastic.CommonSchema.NLog

### ISSUE THREAD

**Issue by yorondevops** [elastic/ecs-dotnet#141]
Hi,

I'm using the NLog ECS Layout (`Elastic.CommonSchema.NLog`) and want to serialize key-value pairs from the MDLC as top-level fields into my JSON log messages.

I'm running into an issue where the fields are serialized into my log messageswith `_metadata` prepended to the field name, making them unindexable. (because Elasticsearch does not allow indexing of fields that start with an `_`)

I would very much appreciate if an optioncould be add to the `Elastic.CommonSchema.NLog` Layout so that  dynamic fields serialized into the log messages from the MDLC could be added without `_metadata` prepended to the field name.

This feature seems to be somewhat related to #104

**Comment by russcam** [comment]
Thanks for opening @yorondevops. This is the same underlying issue as #104. Looking to push a release out that addresses this issue.

I'm going to close this one to consolidate discussion on #104.
