### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by jeffreywstevens** [elastic/ecs-dotnet#143]
Elastic.CommonSchema.NLog

How to enrich / output custom ECS properties such as EventId, EventAction, etc. while using NLog?

Unfortunately, in our environment, we usually just use the nlog.config so that we can manipulate the rules and targets per environment.

 I really want to place a custom properties / traceable GUID,etc.) in the Event (Hopefully EventId) in order to have it used in Elasticsearch as the DocumentId.  We also want to route these properties in a hub.

How can I do that?

**Comment by snakefoot** [comment]
You can explicit add additional metadata as shown in the documentation (Using `<metadata>`):

https://github.com/elastic/ecs-dotnet/tree/master/src/Elastic.CommonSchema.NLog

**Comment by jeffreywstevens** [comment]
Metadata works find with the LogEventInfo properties class.  Still not ideal.  I would have to transform it downstream.

I was thinking I could inherit EcsLayout with a custom class and override EnrichEvent.  I haven't been successful with that yet.

The reason is I want to combine all events in a hub, all using ECS schema using core properties.  These to be logging events combined with actual business events like "electonic-payment-processed" etc.

**Comment by jeffreywstevens** [comment]
I was able to subclass EcsLayout and enrich any of the event properties.
