### ISSUE TITLE
[FEATURE] Turn off/Override Snake Case Serialization of Metadata

### ISSUE THREAD

**Issue by ghost** [elastic/ecs-dotnet#161]
Metadata properties and classes at the top level get renamed with underscores.

For instance:

If I add a class called "ContextInfo" to the LogEventInfo properties collection.  It doesn't matter what the property name is in the dictionary.  The resultant JSON is this has "context_info" instead.
"metadata" :{
  "context_info" : {
 "original_id" : 123345
}
}

Class properties can be controlled with serialization attributes: [JsonProperty("originalId")].  With that I can fix "original_id" to display as "originalId" in the JSON.  

This is causing frustrations with the development team and preventing better adoption of this format.

Can we get better control over the serialization naming?

**Comment by Mpdreamz** [comment]
I agree looking back snake casing the metadata keys violates the principle of least surprise

I've opened: https://github.com/elastic/ecs-dotnet/pull/211 to address this. 

It will be a breaking change for 8.4.0. 

Thanks for opening the issue
