### ISSUE TITLE
[BUG] AssemblyVersion downgrade between 1.5.1 & 1.5.3

### ISSUE THREAD

**Issue by RomainHautefeuille** [elastic/ecs-dotnet#171]
Hi,
I noticed that AssemblyVersion was downgraded from 1.5.0 in 1.5.1 to 1.0.0 in 1.5.3.

![screenshot](https://i.ibb.co/9br57sy/Elastic-Common-Schema-Serilog.png)

This leads to build errors in the following configuration:
- Lib A referencing Elastic.CommonSchema.Serilog 1.5.1.
- Project B referencing lib A and Elastic.CommonSchema.Serilog 1.5.3.
And building project B

> CSC : error CS1705: Assembly 'A' with identity 'A, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' uses 'Elastic.CommonSchema.Serilog, Version=1.5.0.0, Culture=neutral, PublicKeyToken=069ca2728db333c1' which has a higher version than referenced assembly 'Elastic.CommonSchema.Serilog' with identity 'Elastic.CommonSchema.Serilog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=069ca2728db333c1' 

Is this downgrade intended?

**Comment by Mpdreamz** [comment]
It was intended, we use this technique to avoid assembly binding issues by giving all `Major.x` releases the same identify. This allows us to strong name our DLL's without issue. 

The fact we didn't in `1.5.1` is the bug, one we have to live with sadly.

We built and use tooling (https://github.com/nullean/nupkg-validator) to assert our nugetpackages ship dll's with the correctly versions:

See e.g from our CI output:

```
[version] Assembly: 1.0.0.0
[version] AssemblyFile: 1.6.0.0
[version] Informational: 1.6.0-alpha1.54+a4d1bd8f42bc61e76dd37c3016cba3384d41a89f
```

This should prevent this from happening again: :crossed_fingers: 

Thanks for bringing this to our attention @RomainHautefeuille :+1:
