### ISSUE TITLE
Save Enum also as String Values

### ISSUE THREAD

**Issue by squadwuschel** [elastic/ecs-dotnet#175]
**Is your feature request related to a problem? Please describe.**
- When I've Enum Values in my Logoutput, it would be nice if I could see the String Values too and not only the Numbers.
- If you have lage Enums you can't remember every number related string name and in the logs it would be nice to see the names too

**Describe the solution you'd like**
- show also the Enum names to the numbers

**Comment by Mpdreamz** [comment]
I tried to reproduce this in: #260 

At least using Microsoft.Extensions.Logging this is already the case. 

Closing this for now but feel free to reopen if this is still broken!
