### ISSUE TITLE
[Question] Parsing back log files create by ECS for Serilog.

### ISSUE THREAD

**Issue by LiorBanai** [elastic/ecs-dotnet#199]
Hi,
I want to create a parser for exist log file for my https://github.com/Analogy-LogViewer/Analogy.LogViewer application.

Is there an example how to read back a file? All the units test seems to only write logs.

**Comment by andreycha** [comment]
Hi,

I guess you can just read the log file using `File.ReadAllLines()` and then parse every line using `EcsDocument.Deserialize()`. You'll need to reference `Elastic.CommonSchema` package for that.

**Comment by LiorBanai** [comment]
@andreycha Thanks, I'll try it.

**Comment by LiorBanai** [comment]
BTW, are the latest changed released as nuget? The last one is from 2021

**Comment by andreycha** [comment]
No. Looks like the plan is to upgrade the library right to 8.4.0, I believe you can follow it here: https://github.com/elastic/ecs-dotnet/issues/197

**Comment by LiorBanai** [comment]
@andreycha  Thanks!

**Comment by Mpdreamz** [comment]
Thanks for answering @andreycha :+1: Closing this out while we gear up to release #197
