### ISSUE TITLE
Entire ECS schema is available but no way to fill it up

### ISSUE THREAD

**Issue by alaw-emoney** [elastic/ecs-dotnet#20]
The formatted log contains data within a hard-coded set of fields, which are very useful data points, but leaves a lot of the schema unused, and instead puts log event data into "_metadata". There appears to be no way to move data from the log event to somewhere in the schema. There should be a hook into the formatter such that more properties of the log event can be out of "_metadata" and into the right place in the schema.

Request:
Given the logging user logs properties (e.g. from context), and the user specifies a mapping from the log event to the schema, the formatted text should have the additional schema fields populated.

**Comment by Mpdreamz** [comment]
Now implemented as of #24 we'll do another release shortly. 

Thanks for the PR and issue @alaw-emoney 👍
