### ISSUE TITLE
Elastic.CommonSchema discrepancy

### ISSUE THREAD

**Issue by alaw-emoney** [elastic/ecs-dotnet#21]
Might just be a point of ignorance but...
I noticed that in Elastic.CommonSchema.Serilog, if I remove the project reference to Elastic.CommonSchema and instead reference the nuget package Elastic.CommonSchema 1.2.0.-alpha1, it doesn't compile (the serialize method is missing). Do we know where the discrepancy came from?

**Comment by codebrain** [comment]
Hi @alaw-emoney.

This change was added in dc75b6ee831f532c8e62a1033e4287fbdfa9ad0f , which was after the `1.2.0-alpha1` release, hence the binary compatibility issue you are seeing.

We are looking to release a `1.3.0-beta1` version of the assembly very shortly, which will overcome the issue you are experiencing.

These projects have been in flux quite a lot, hence the pre-release labelling, but once they have settled down we will look towards giving some assurances on our binary compatibility approach.
