### ISSUE TITLE
[FEATURE] [Elastic.CommonSchema.Serilog] Support LogContext writing to labels node

### ISSUE THREAD

**Issue by odin568** [elastic/ecs-dotnet#225]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**:

**Is your feature request related to a problem? Please describe.**
I would like to do more structured logging with SeriLog and ECS format. KV pairs should be placed to labels fields (as it works for java integrations). While adding static information (relevant for all log messages) can be done, I want to add dynamic labels on the fly in my code to enable better tracing, like a ShipmentId in the code example below.

**Describe the solution you'd like**
Having `.Enrich.FromLogContext()` active I would like to set labels ecs conform using the LogContext like
```c#
            using (LogContext.PushProperty("labels.ShipmentId", shipmentId))
            {
                        _logger.Information(...)
            }
```
This should serialize in the json like 
```json
...
labels: {
   "ShipmentId": "42"
} ...
```
Currently I dont't see it placed anywhere in the resulting json.

**Describe alternatives you've considered**
Writing custom format on my own....

**Additional context**
-

**Comment by andreycha** [comment]
I believe log context properties are written to `metadata` JSON property (which is not official part of ECS).

**Comment by odin568** [comment]
Ah yes you are right, missed that somehow.

My challenge is that I am in a very heterogenous environment having legacy apps, up2date dotnetcore services, java services, cloud functions, etc.
To bring logs together we try to stick to ECS format and it would be nice if labels would be supported. I use them regulary to enrich logs with structured information to trace something across applications.

**Comment by andreycha** [comment]
As far as I understand, all the log properties (from log context and from structured log messages) are, strictly speaking, not compatible with labels. According to spec, `labels` should not contain nested objects and their values are indexed as keywords. While the properties can of course include complex objects.

While `metadata` is not part of ECS spec, it is for example included as `flattened` field in Filebeat indices by default which allows to store anything in there.

As an option, you might have an ingest pipeline which copies/moves atomic values from `metadata` to `labels`.

**Comment by odin568** [comment]
Got it, thanks for explanation.
Only thing that I feel inconsistent is when I compare with java implementation, see ticket https://github.com/elastic/ecs-logging-java/issues/60
In java I can define MDCContext with Key "labels.someKey" - "someValue" and this gets propagated like that.
Of course you should not do "labels.someKey.someSubKey" - not sure what would happen in the java implementation...

**Comment by andreycha** [comment]
Difference here is that Logback MDC allows only string values and then of course it's safe to put them into `labels`. While Serilog's log context and generally structured logging in .NET allow anything. So there are differences in how logs from different frameworks are mapped into ECS. Even this repository has enough small discrepancies between NLog, Serilog, and log4net implementations.

Unfortunately, while ECS is surely a great thing, one still need some tinkering here and there.

Luckily, Serilog implementation allows customization (see `MapCustom`), so as another option you can fill `labels` in there as well.

**Comment by odin568** [comment]
Ok, that is a valid point.
Yes I use MapCustom already to fill some fixed fields like service.name, service.version and also already providing service.environment by an inherited service object.
But what I need in this case is a dynamic field. So when creating the logmessage I want to add some labels which might be different on every run/call.
How could I manage this?

**Comment by andreycha** [comment]
I could imagine a couple of options:
1) More coarse-grained. Iterate through all properties of a log event (alternatively, through `metadata` entries of an ECS event) and copy/move them to labels.
2) More fine-grained approach. Iterate through all properties of a log event (alternatively, through `metadata` entries of an ECS event) which starts from `"labels."` and move them to `Labels` property of an ECS event dropping `"labels."` prefix from property name. This prefix effectively becomes your conventions on which log properties should stay in `metadata` and which will go to `labels`.

In both cases you might additionally want to check that property value is an atomic value.

**Comment by Mpdreamz** [comment]
The new major version of the library will be `labels` aware out of the box.

Unknown `string` and `boolean` values will be treated as `labels` keywords.

```csharp
using (LogContext.PushProperty("ShipmentId", "my-shipment-id"))
using (LogContext.PushProperty("ShipmentAmount", 2.3))
{
	logger.Information("Logging something with log context");
}
```

Will automatically add `labels.ShipmentId` and `metadata.ShipmentAmount`. 

Fun side-note our `metadata` predates `labels` in ECS :smile:, now that we have a better "bucket" for keyword key value pairs I think this helps realigns ECS.NET closer to ECS again.

Also assigning ECS fields will be possible from the message template itself for fields not part of an array. 

e.g

```csharp
logger.Information("Directly assigning {ServiceName} is now easier", "my-service");
```

Will set `service.name` on the resulting ECS json and no longer `metadata.ServiceName`.
