### ISSUE TITLE
serviceName in formatters 

### ISSUE THREAD

**Issue by douglaswittner** [elastic/ecs-dotnet#226]
I notice serviceName is being emitted in the main branch in the Nlog formatting. This feature was coded and merged to main a while ago. I do no see this in any tag. 

I believe myself and others would need this for APM correlation to the logs.

**Comment by muralivenkataraman** [comment]
I am working with a client here and they are interested to know the release date as well.

**Comment by Mpdreamz** [comment]
closing this in favor of #197, we'll comment on that thread when we will release the new version that should have service name by default in NLOG logs. 

Thanks for the nudge though, truly appreciated ! :+1:
