### ISSUE TITLE
[BUG] Correlation Log not working when using Auto Instrumentation (Profiler) or Zero code change (Startuphook)

### ISSUE THREAD

**Issue by karpediemnow** [elastic/ecs-dotnet#227]
Hi Everyone,

following the documentation about Log correlation ( [Link](https://www.elastic.co/guide/en/apm/agent/dotnet/current/nlog.html) )

I have added the Elastic.Apm.NLog.dll and the following entries into NLog.config file

![image](https://user-images.githubusercontent.com/1301695/202998538-d4abf225-ec2a-420d-82ed-c99fef9c8a90.png)

but the ElasticApmTraceId and ElasticApmTransactionId are not showing in the log :frowning:

I'm using [elastic_apm_profiler_1.18.0](https://github.com/elastic/apm-agent-dotnet/releases/download/v1.18.0/elastic_apm_profiler_1.18.0.zip) and [Elastic.Apm.NLog v 1.5.3](https://www.nuget.org/packages/Elastic.Apm.NLog).

Is Log correlation incompatible with [Profiler](https://www.elastic.co/guide/en/apm/agent/dotnet/master/setup-auto-instrumentation.html)/[Startuphook ](https://www.elastic.co/guide/en/apm/agent/dotnet/master/setup-dotnet-net-core.html#zero-code-change-setup)instrumentation?

Thanks

**Comment by z1c0** [comment]
Hi @karpediemnow,
one question before we start a more profound investigation, so we can rule this out:

Is there definitely an active Transaction when the log statement is written? Otherwise, TraceId and TransactionId are not present.

**Comment by Mpdreamz** [comment]
For log correlation the fields should be `trace.id` and `transaction.id`.
