### ISSUE TITLE
[BUG] Unable to use ConfigureLogging in ASP.NET WebApi core

### ISSUE THREAD

**Issue by HubDevUser** [elastic/ecs-dotnet#265]
**ECS integration/library project(s) (e.g. Elasticsearch.Extensions.Logging)**:

**ECS schema version (e.g. 1.4.0)**:

**ECS .NET assembly version (e.g. 1.4.2)**:1.6.0-alpha1

**Elasticsearch version (if applicable)**:

**.NET framework / OS**: NET6 Windows

**Description of the problem, including expected versus actual behavior**:
In a console application using Host this works fine, but when dealing with WebHost (Core3.1) or WebApplication (6.0). writing to elastic search does not seem to work.

**Steps to reproduce**:
 1. create asp net web api solution (net 6)
 2. in program.cs

```csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Host.ConfigureLogging((hostContext, loggingBuilder) =>
                {

        loggingBuilder.AddElasticCloud("MY_CLOUD_ID",  "MyAPIKey");
                });
    var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
 ```
 
 3. this is also see in  WebHost netcore3.1
 ```csharp
  WebHost
            .CreateDefaultBuilder(args)
            .ConfigureLogging((hostContext, loggingBuilder) =>
            {
                loggingBuilder.AddElasticCloud("MY_CLOUD_ID",  "MyAPIKey");
            })
            .UseStartup<T>();
```

this however works fine in a Console:

 ```csharp
Host.CreateDefaultBuilder(args)
                .ConfigureLogging((hostContext, loggingBuilder) =>
                {
				loggingBuilder.AddElasticCloud("MY_CLOUD_ID",  "MyAPIKey");
})
```

**Comment by Mpdreamz** [comment]
I didn't quite validate this on `1.6.0-alpha1` because it will be obsolete as soon as we release 8.4.0-alpha1

I did create https://github.com/elastic/ecs-dotnet/pull/267 to add an example project and improve our OOTB experience for Elasticsearch.Extensions.Logging and ASP.NET 

Be mindful that the default configuration for ASP.NET has 

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
```

This means that you won't see the OOTB request logging unless you change it to

```diff
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
-      "Microsoft.AspNetCore": "Warning"
+      "Microsoft.AspNetCore": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

**Comment by HubDevUser** [comment]
here is my appsettings on WeatherForecast

`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Information"
    }
  },
  "AllowedHosts": "*"
}
`

i still dont see any logging,  i added an informational trace as well but i cant see it in elastic 

![image](https://user-images.githubusercontent.com/11462841/218811618-746ecf2b-1791-4bc9-afd4-3f36be806e99.png)

**Comment by HubDevUser** [comment]
does your PR address this ? whats the working version ? 1.6.0-alpha is the only published version https://www.nuget.org/packages/Elasticsearch.Extensions.Logging/

**Comment by Mpdreamz** [comment]
Yeah it should the `example` app does exactly what your shared code is doing. 

A new update will be released soon!

**Comment by HubDevUser** [comment]
this works L

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();

builder.Host.ConfigureLogging((_, loggingBuilder) =>
{
	loggingBuilder.AddElasticsearch();

	void configure(ElasticsearchLoggerOptions options)
	{
		options.ShipTo.ConnectionPoolType = ConnectionPoolType.Cloud;
		options.ShipTo.CloudId = "id";
		options.ShipTo.ApiKey = "key";
	}

	builder.Services.Configure((Action<ElasticsearchLoggerOptions>)configure);

});
var app = builder.Build();
app.UseAuthorization();
app.MapControllers();
app.Run();



this does not :


namespace WebApplication5
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureLogging((builder) =>
                    {
                        builder.AddElasticsearch();

                        void configure(ElasticsearchLoggerOptions options)
                        {
                            options.ShipTo.ConnectionPoolType = Elastic.Ingest.ConnectionPoolType.Cloud;
                            options.ShipTo.CloudId = "id";
                            options.ShipTo.ApiKey = "key";
                        }

                        builder.Services.Configure((Action<ElasticsearchLoggerOptions>)configure);
                    })
                    .UseStartup<Startup>();
                });
    }
}


any pointers how i can get this working with IWebHostBuilder instead of WebApplication?

**Comment by HubDevUser** [comment]
The IWebHost scenario only works on latest of the repo, please release a new nuget package
