### ISSUE TITLE
[BUG] NullReferenceException in LogEventConverter when filling http.ResponseMimeType from ContentType log property

### ISSUE THREAD

**Issue by vincevriend** [elastic/ecs-dotnet#273]
**ECS integration/library project(s):** Elastic.CommonSchema.Serilog

**ECS schema version:** 8.4.0

**ECS .NET assembly version:** 8.4.0-alpha1

**.NET framework / OS:** Windows

**Description of the problem, including expected versus actual behavior:**

I first encountered this in my own application but it's also present in the example project.  

Running the aspnetcore-with-serilog example from this repo with the Visual Studio debugger attached will throw a NullReferenceException when browsing to the application URL.

It occurs in `Elastic.CommonSchema.Serilog/LogEventConverter.cs` at line 331.

```C#
if (e.TryGetScalarPropertyValue(SpecialKeys.ContentType, out var contentType))
{
    http ??= new Http();
    http.ResponseMimeType = contentType.Value.ToString(); // Line 331, contentType.Value is null here
}
```

**Steps to reproduce**:
 1. Run aspnetcore-with-serilog from this repo with the Visual Studio debugger attached
 2. Browse to http://localhost:5000
 3. The exception will be thrown

**Comment by Mpdreamz** [comment]
:pray: Thank you for finding this bug! 

Opened https://github.com/elastic/ecs-dotnet/pull/275 to address this.

**Comment by Mpdreamz** [comment]
@vincevriend I pushed another update to nuget `8.4.0-alpha2` that should address this!

**Comment by vincevriend** [comment]
Thx! i can confirm that the exception also no longer occurs in my application using `8.4.0-alpha2`.
