### ISSUE TITLE
ECS version tags

### ISSUE THREAD

**Issue by webmat** [elastic/ecs-dotnet#3]
Could you adjust the ECS version names a little bit? There's two things I see that could be confusing about them, in the readme.

- ECS always explicitly includes all 3 numbers in the version number, including `.0` patch. So instructing people to construct the URL with the "1.2" tag will give them a 404. They'll figure it out, but it's an annoyance we can avoid :-)
- Also the actual tag in Git includes a leading `v`.

So the full 1.2 tag actually looks like `v1.2.0` :-)

Loving the readme otherwise, good work!

**Comment by codebrain** [comment]
Thanks @webmat - I have corrected the README and fixed the version number references.
