### ISSUE TITLE
[FEATURE] Allow basic auth for non-cloud node types

### ISSUE THREAD

**Issue by irontoby** [elastic/ecs-dotnet#308]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**: Elasticsearch.Extensions.Logging

**Is your feature request related to a problem? Please describe.**
Our self-hosted Elasticsearch instance requires HTTP basic auth. (Note, we are using the docker-compose setup from [this project](https://github.com/deviantony/docker-elk#how-to-disable-paid-features)). However, the `Username` and `Password` config settings are [only used for Cloud node types](https://github.com/elastic/ecs-dotnet/blob/main/src/Elastic.Extensions.Logging/README.md#configuration-settings).

**Describe the solution you'd like**
Allow using `Username`/`Password` for single node pools also.

**Describe alternatives you've considered**
I was able to work around this by using e.g. `https://username:password@example.com` as the URL but it would be better if I could store the username/password separately and provide them via secure means (Azure KeyVault in our case).

**Additional context**
It looks like fixing this would also involve updating [`SingleNodePool`](https://github.com/elastic/elastic-transport-net/blob/cf5c8c94a6fb7d8658712e6accd39f9100e92090/src/Elastic.Transport/Components/NodePool/SingleNodePool.cs) from `elastic-transport-net` to have the same `AuthenticationHeader` as [`CloudNodePool`](https://github.com/elastic/elastic-transport-net/blob/cf5c8c94a6fb7d8658712e6accd39f9100e92090/src/Elastic.Transport/Components/NodePool/CloudNodePool.cs) so I wasn't sure if I should file an issue in both places. I didn't see any existing related issues in that repo either.

**Comment by Mpdreamz** [comment]
Through code you can always create your own transport (or reuse one from an ElasticsearchClient): 

```csharp
loggingBuilder.AddElasticsearch(CreateTransport(), loggerOpts =>
{
	//
}, channelOpts =>
{
	//
});
```

```csharp
static HttpTransport CreateTransport()
{
	var pool = new SingleNodePool(new Uri("http://localhost:9200"));
	var config = new TransportConfiguration(pool)
		.Authentication(new BasicAuthentication("u", "p"));
	return new DefaultHttpTransport(config);

}
```



Through config however


```
  "Logging": {
    "Elasticsearch": {
      "Tags": [ "Development", "Example" ],
      "IndexOffset": "00:00",
      "IsEnabled": true,
      "IncludeScopes": true,
      "IncludeHost": true,
      "IncludeProcess": true,
      "IncludeUser": true,
      "ShipTo": {
        "NodePoolType": "SingleNode",
        "NodeUris": [ "http://localhost:9200" ],
		"Username": "u",
		"Password": "p"
      }
    },
    "LogLevel" : {
      "Default": "Trace",
      "Microsoft": "Warning"
    }
  }
}
```

`Username`/`Password` and `ApiKey` currently only will be applied when `NodePoolType` == 
`Cloud`. 

I will create a PR to rectify this, thank you for bringing this to our attention @irontoby!

**Comment by irontoby** [comment]
@Mpdreamz thanks for the update, I saw the option to add my own HttpTransport but once I started looking through the code I wasn't comfortable enough in creating my own instance and being sure I didn't miss anything. But I'll give your code a try!

**Comment by Mpdreamz** [comment]
#313 should fix configuring authentication through config.
