### ISSUE TITLE
EcsTextFormatter over-escapes output when write to file (stream?)

### ISSUE THREAD

**Issue by MikhailIzvekov** [elastic/ecs-dotnet#31]
**ECS version**: 1.4.0 (assembly version: 1.4.0-beta1)

**.NET framework / OS**: .Net Core 2.2 / Windows

**Description of the problem, including expected versus actual behavior**:
Non ASCII symbols got escaped, users can't read logs.

Actual (as WriteTo.File):

```
...
	"message": "\u042F\u0437\u044B\u043A: { \u0417\u043D\u0430\u0447\u0435\u043D\u0438\u0435: \u0022\u0420\u0443\u0441\u0441\u043A\u0438\u0439\u0022 }",
	"_metadata": {
		"data": {
			"properties": [{
				"name": "\u0417\u043D\u0430\u0447\u0435\u043D\u0438\u0435",
				"value": {
					
				}
			}]
		}
	},
...
	"event": {
		"severity": 2,
		"timezone": "RTZ 3 (\u0437\u0438\u043C\u0430)",
		"created": "2020-01-14T10:42:16.8076199+04:00"
	},
...
```

Expected  (as WriteTo.Console):
```
...
	"message": "Язык: { Значение: \"Русский\" }",
	"_metadata": {
		"data": {
			"properties": [{
				"name": "Значение",
				"value": {
					
				}
			}]
		}
	},
...
	"event": {
		"severity": 2,
		"timezone": "RTZ 3 (зима)",
		"created": "2020-01-14T10:44:23.8543233+04:00"
	},
...
```

**Steps to reproduce**:
```csharp
      Log.Logger = new LoggerConfiguration()
        .WriteTo.Console(new EcsTextFormatter())
        .WriteTo.File(new EcsTextFormatter(), "d:\\log.log")
        .CreateLogger();

      Log.Logger.Information("Язык: {@Data}", new { Значение = "Русский" });
```

**Cause**
Seems like Base.Serialize should create Utf8JsonWriter with `new JsonWriterOptions {Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping }`.
Now `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` only used in JsonSerializer.Serialize.

**Comment by codebrain** [comment]
Thanks for raising, fixed in commit https://github.com/elastic/ecs-dotnet/pull/33/commits/13e1b5f8a178e8d1e6f816c907ff7d74d969ab74
