### ISSUE TITLE
[BUG] Failure to create component template `$ecs_8.6.0_agent` for logs-dotnet-*

### ISSUE THREAD

**Issue by viniciusfonseca-trt17** [elastic/ecs-dotnet#312]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**:
Elastic.Extensions.Logging 8.6.0
**ECS schema version (e.g. 1.4.0)**:
8.6.0
**ECS .NET assembly version (e.g. 1.4.2)**:
8.6.0
**Elasticsearch version (if applicable)**:
8.8.1
**.NET framework / OS**:
.NET 7.0 / Windows 10
**Description of the problem, including expected versus actual behavior**:

**Steps to reproduce**:
 1. Install Docker Desktop on Windows and setup Elasticsearch and Kibana following the tutorial (https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
 2. Create a .NET 7.0 console application and install the library Elastic.Extensions.Logging 8.6.0
 3. Create a configuration file appsettings.json as follows:
![image](https://github.com/elastic/ecs-dotnet/assets/100166068/6edac2ec-8481-4955-8be7-3e94b78d4f4f)
 4. Create Program.cs:
![image](https://github.com/elastic/ecs-dotnet/assets/100166068/c36c1952-28fa-4c26-ac0e-a51c88944651)
 5. Then run the console application and the exception is thrown on Build():
![image](https://github.com/elastic/ecs-dotnet/assets/100166068/893f1d5c-1373-4c9f-a825-6a03815cca7d)
6. Inspecting the request with Fiddler, I've found the underlying error:
`{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_component_template/ecs_8.6.0_agent]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_component_template/ecs_8.6.0_agent]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}`
7. I've tried to create a new user with kibana_admin role and adding it's credentials with Username and Password properties inside ShipTo as described by the tutorial (https://www.elastic.co/guide/en/ecs-logging/dotnet/current/extensions-logging-data-shipper.html), but it made no difference, since this setting seems to be used only for cloud.

**Comment by lewinskimaciej** [comment]
Have you tried configuring transport?
```csharp
var pool = new SingleNodePool(nodeUri);
var transportConfig = new TransportConfiguration(pool)
                .Authentication(new BasicAuthentication(Username, Password));

var sinkOptions = new ElasticsearchSinkOptions(new DefaultHttpTransport(transportConfig));

(...).WriteTo.Elasticsearch(sinkOptions);
```

Also as you can see, exception message is pretty useless there, as I had similar issue recently, I made a PR for this in elastic-ingest-dotnet:
https://github.com/elastic/elastic-ingest-dotnet/pull/37

**Comment by lewinskimaciej** [comment]
Have you tried configuring Transport directly like this?
```csharp
    logging.AddConsole().AddDebug().AddElasticsearch(opt =>
    {
        var nodeUri = new Uri("http://localhost:9200");
        var config = new TransportConfiguration(nodeUri)
            .Authentication(new BasicAuthentication("username", "password"));

        opt.Transport = new DefaultHttpTransport(config);
    });
```

As for the useless exception message, I also had an issue with it, made a PR: 
https://github.com/elastic/elastic-ingest-dotnet/pull/37
but I can't tell whether/when it will get merged.

**Comment by Mpdreamz** [comment]
Thanks @lewinskimaciej we updated transport to provide a better exception message if a bad authentication happens on the ping to Elasticsearch before the actual API call. 

I also opened #323 to document the minimum privileges needed to use the datashippers of this repository.
