### ISSUE TITLE
[BUG] Logs not being parsed properly in Kibana APM app

### ISSUE THREAD

**Issue by LeaTaka** [elastic/ecs-dotnet#354]
`Microsoft.NET.Sdk.Web`
`net6.0`

`Elastic.Apm.NLog Version=8.6.1`
`Elastic.CommonSchema.NLog Version=8.6.1`
`Elastic.Apm.NetCoreAll Version=1.25.2`
`Elastic.Apm.Extensions.Logging Version=1.25.2`
`NLog.Web.AspNetCore Version=5.*`
`NLog Version=5.*`
`NLog.Extensions.Logging Version=5.*`

`ECK: 2.10`
`Elasticsearch, Kibana, Fleet, Agents: 8.11.3`

**The problem:**
Application logs (_logger.LogInformation, etc..) are parsed correctly when Ilogger is used.
The erroneous parsing is visible in the Kibana APM app on the Log tab of the Service ans also on the Log tab of a Trace when correlating logs to traces. I included screenshots of the the Log tab of the Services, in red the loglines that have Elastic .json documents attached in the included zipfile.
I'm not sure if either the Kibana is the problem or one of the libraries I used.

**Goal:**
Our goal is to use EcsLayout with Nlog and Ilogger

**Reproduction:**
Please find a zipfile attached with the following examples for reproduction purposes;
[Ecs-Nlog-Iloggler.zip](https://github.com/elastic/ecs-dotnet/files/13773758/Ecs-Nlog-Iloggler.zip)

- app-10-dotnet application with Ilogger implementation
- app-10-dotnet console logs example
- app-10-dotnet screenshot of the behaviour in Kibana APM app on the log tab
- app-10-dotnet Elasticsearch document (the line in red on the .png screenshot)
--
- app-11-dotnet application _without_ Ilogger implementation
- app-11-dotnet console logs example
- app-11-dotnet screenshot of the behaviour in Kibana APM app on the log tab
- app-11-dotnet Elasticsearch document (the line in red on the .png screenshot)

Hope you can help solving this problem.

**Comment by Mpdreamz** [comment]
I think this is more of an Elastic Agent log file integration SDH. 

When they don't set up NLOG as the `ILogger` implementation for Asp.NET Core the logoutput is:


````text
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {9bb6fadb-39b3-475b-afd8-af8c7732593f} may be persisted to storage in unencrypted form.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
{"@timestamp":"2023-12-26T11:03:16.8216081+00:00","log.level":"Info","message":"Requested /up endpoint for checking health status of app10","ecs.version":"8.6.0","log":{"logger":"app_11_csharp.Controllers.HealthCheckController","origin.file.name":"","origin.function":""},"span.id":"01f176c1ee9ecf91","trace.id":"5b4140469af762759b7c0207aed2236e","transaction.id":"01f176c1ee9ecf91","agent":{"type":"Elastic.CommonSchema.NLog","version":"8.6.1\u002B88f2bc81a0b7440e4059e323e610bb03df61862c"},"event":{"created":"2023-12-26T11:03:16.8216081+00:00","severity":6,"timezone":"Coordinated Universal Time"},"host":{"ip":["10.42.3.20"],"name":"app-11-dotnet-64b9d9fc56-ckg5r"},"process":{"executable":"/usr/share/dotnet/dotnet","name":"dotnet","pid":7,"thread.id":18,"title":"1.0.0.0"},"server":{"user":{"name":"UserUnknown"}},"service":{"name":"app-11-dotnet","node.name":"","version":"1.0.0"}}
```


When it **is** setup as the `ILogger` implementation the FULL output is ECS:

```json
{"@timestamp":"2023-12-26T11:01:31.1462677+00:00","log.level":"Warn","message":"Using an in-memory repository. Keys will not be persisted to storage.","ecs.version":"8.6.0","log":{"logger":"Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository","origin.file.name":"","origin.function":""},"labels":{"EventName":"UsingInMemoryRepository"},"agent":{"type":"Elastic.CommonSchema.NLog","version":"8.6.1\u002B88f2bc81a0b7440e4059e323e610bb03df61862c"},"event":{"code":"50","created":"2023-12-26T11:01:31.1462677+00:00","severity":4,"timezone":"Coordinated Universal Time"},"host":{"ip":["10.42.3.19"],"name":"app-10-dotnet-86cbb67678-57z4b"},"process":{"executable":"/usr/share/dotnet/dotnet","name":"dotnet","pid":7,"thread.id":1,"title":"1.0.0.0"},"server":{"user":{"name":"UserUnknown"}},"service":{"name":"app-10-dotnet","node.name":"","version":"1.0.0"},"metadata":{"EventId":50}}
```

That first line that is printed by ASP.NET core now too uses the NLOG ECS formatting. 

This is expected and working as it should.

I **think* they are using the kubernettes consoleoutput integration but I am not sure how it detects json.

**Comment by bart-medfar** [comment]
I have the same issue when using serilog + elastic sink + apm on .net 8 web app

**Comment by LeaTaka** [comment]
Example pics 
attached of when configuring collumns in Kibana Logs ( not possible on the log tabs in the Kibana APM app )

![1 add_msg_field_in_logs_settings](https://github.com/elastic/ecs-dotnet/assets/44557739/a7f51058-4548-4a6b-9768-916c1a6d035d)
![2 show_difference_between_Message_and_message_fields](https://github.com/elastic/ecs-dotnet/assets/44557739/d27f71c9-621f-46f2-a20b-c2fcd4081dcf)

**Comment by Mpdreamz** [comment]
Thanks for opening this issue @LeaTaka ultimately this is a bug/issue in kibana:

https://github.com/elastic/kibana/issues/176013

I tend to agree the special computed `Message` column should always prefer `message` over anything computed.

**Comment by LeaTaka** [comment]
> Thanks for opening this issue @LeaTaka ultimately this is a bug/issue in kibana:
> 
> [elastic/kibana#176013](https://github.com/elastic/kibana/issues/176013)
> 
> I tend to agree the special computed `Message` column should always prefer `message` over anything computed.

Hi there Martijn, thanks for forwarding this to the Kibana team 👍

**Comment by Mpdreamz** [comment]
Closing this since upstream ticket got closed too: https://github.com/elastic/kibana/issues/176013

Trusting the Logs embeddable will work better but will keep an eye out.

Looking forward to a next ticket Jasper 😸
