### ISSUE TITLE
Is it possible to write to elastic from log4net using this library ?

### ISSUE THREAD

**Issue by MalkaGit** [elastic/ecs-dotnet#358]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**:

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thompson-tomo** [comment]
@MalkaGit have u taken a look at https://github.com/elastic/ecs-dotnet/blob/main/src/Elastic.CommonSchema.Log4net/README.md which talks about the options.

**Comment by pumikiPum** [comment]
Thank you so much for your replay .

few short questions:
1. Is the lib official?
2. Is there a way to select only some of the field s , to improve computation and network time ?
3. 3. Are there any known issues about js performance of the lib ?
4. 4. I am responsible for handling the name of the index (table) to which the data will be written to Elasticsearch. Correct ?
5. 5. Is there any best practice  regarding the index name ? Eg, separate index per day
6. 
thank you so much 
7.

**Comment by thompson-tomo** [comment]
@pumikiPum yes it is an official library by Elastic. The library by default populates values into a number of properties which can not be controlled.

**Comment by Mpdreamz** [comment]
Thanks for your answers @thompson-tomo I think we can close this now.
