### ISSUE TITLE
[FEATURE] Include sequence id under event details

### ISSUE THREAD

**Issue by thompson-tomo** [elastic/ecs-dotnet#386]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**:
Elastic.CommonSchema.Nlog

**Is your feature request related to a problem? Please describe.**
Enable clearly sequencing of logs

**Describe the solution you'd like**
I would like the sequenceId which is available as part of the logevent to be recorded under my event as defined in the spec

**Describe alternatives you've considered**
Rely on timestamps

**Additional context**
Definition as per: https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-sequence

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/ecs-dotnet/pull/392 to address this thanks @thompson-tomo

**Comment by thompson-tomo** [comment]
thanks @Mpdreamz i noticed in my testing/debugging when i instpected the logevent it was being incremented on each run through but if it is planned to be removed that is also ok.
