### ISSUE TITLE
BenchmarkDotNetExporter nuget is missing dependency to Elasticsearch.Net

### ISSUE THREAD

**Issue by robertlyson** [elastic/ecs-dotnet#41]
Hi 👋 ,

Just wanted to try out what you have been cooking lately - I've created sample console app and tried to use `ElasticsearchBenchmarkExporter` exporter with sample `Md5VsSha256` benchmark. After running the benchmark I got following  exception

```
/usr/local/share/dotnet/dotnet /Users/robertlyson/projects/BenchmarkDotNetExporter/Exporter/bin/Debug/netcoreapp3.0/Exporter.dll
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'. The system cannot find the file specified.

File name: 'Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'
   at Elastic.CommonSchema.BenchmarkDotNetExporter.ElasticsearchBenchmarkExporter..ctor(ElasticsearchBenchmarkExporterOptions options)
   at Exporter.Program.Main(String[] args) in /Users/robertlyson/projects/BenchmarkDotNetExporter/Exporter/Program.cs:line 27



Process finished with exit code 6.
```

Installing `Elasticsearch.Net` 7.x into the test project resolves the issue. Looks like `Elastic.CommonSchema.BenchmarkDotNetExporter` package is missing dependency to Elasticsearch.Net?

**ECS version**: 1.4.0

**Elasticsearch version (if applicable)**: 7.5.2

**.NET framework / OS**: .net core 3.0 / macOS

**Description of the problem, including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create new .net core console project
 2. Install Elastic.CommonSchema.BenchmarkDotNetExporter [version 1.4.0](https://www.nuget.org/packages/Elastic.CommonSchema.BenchmarkDotNetExporter/1.4.0)
 3. Try to run this benchmark 

```
var options = new ElasticsearchBenchmarkExporterOptions("http://localhost:9200")
{
    GitBranch = "externally-provided-branch",
    GitCommitMessage = "externally provided git commit message",
    GitRepositoryIdentifier = "repository"
};
var exporter = new ElasticsearchBenchmarkExporter(options);

BenchmarkRunner.Run(typeof(Md5VsSha256), DefaultConfig.Instance.With(exporter));
```

Fails with 
```
/usr/local/share/dotnet/dotnet /Users/robertlyson/projects/BenchmarkDotNetExporter/Exporter/bin/Debug/netcoreapp3.0/Exporter.dll
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'. The system cannot find the file specified.

File name: 'Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'
   at Elastic.CommonSchema.BenchmarkDotNetExporter.ElasticsearchBenchmarkExporter..ctor(ElasticsearchBenchmarkExporterOptions options)
   at Exporter.Program.Main(String[] args) in /Users/robertlyson/projects/BenchmarkDotNetExporter/Exporter/Program.cs:line 27



Process finished with exit code 6.
```

**Comment by codebrain** [comment]
Thanks for raising @robertlyson 

The issue here is that the `Elastic.CommonSchema.BenchmarkDotNetExporter` assembly has a private asset reference to the client.

See:
https://github.com/elastic/ecs-dotnet/blob/9224406142e176820903cc92cb93aedf34907da8/src/Elastic.CommonSchema.BenchmarkDotNetExporter/Elastic.CommonSchema.BenchmarkDotNetExporter.csproj#L15

The documentation on these references (https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) indicates that:

> **PrivateAssets** : These assets will be consumed but won't flow to the parent project

@Mpdreamz - how do you feel about dropping the `PrivateAssets` parameter and creating a reference  to Elasticsearch.Net >= 7.5.0 ?

**Comment by Mpdreamz** [comment]
@codebrain yes lets do that for now 👍
