### ISSUE TITLE
[BUG] Uncontrolled growth of memory consumption

### ISSUE THREAD

**Issue by XCiteForever** [elastic/ecs-dotnet#420]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**: Elastic.Extensions.Logging

**ECS schema version (e.g. 1.4.0)**: latest

**ECS .NET assembly version (e.g. 1.4.2)**: latest

**.NET framework / OS**:  .NET 8.0 / Any OS

Setting OutboundBufferMaxLifetime to Timespan.Zero will cause memory consumption to continually increase.

**Steps to reproduce**:
 1.
Configure connection as:
`
 services
     .AddLogging(c =>
     {
         c.AddElasticsearch(lo => {}, co => {
             co.BufferOptions.OutboundBufferMaxLifetime = TimeSpan.Zero;
         });
     });
`
![image](https://github.com/user-attachments/assets/5b351aa4-1be8-446d-8bfd-005d9e3c3314)

**Comment by Mpdreamz** [comment]
I couldn't quite reproduce this but because `TimeSpan.Zero` basically causes export buffers of size `1` the inbound channel will never be drained fast enough and so should grow.

I opened https://github.com/elastic/elastic-ingest-dotnet/pull/72 to address this.
