### ISSUE TITLE
Retrieve or Customize _id of elastic search log

### ISSUE THREAD

**Issue by SumitMSunhala** [elastic/ecs-dotnet#424]
Hi,
I am new to this, and I am wondering if it is possible to achieve any one of the following:
1- Can we get the _id field of elastic search, while we forward the logs?
OR
2- Can we somehow using any enricher or anything else, decide what the _id should be?

**Comment by Mpdreamz** [comment]
This is not supported nor will we add support for this. 

Logs are time series data and Elasticsearch does a lot of magic to ensure `_id`'s in time series data compress are in order etc.
