### ISSUE TITLE
Increase elastic apm dependency version in Elastic.Apm.SerilogEnricher

### ISSUE THREAD

**Issue by gregkalapos** [elastic/ecs-dotnet#61]
In order to fix https://github.com/elastic/ecs-dotnet/issues/58 I opened https://github.com/elastic/apm-agent-dotnet/pull/753 in the .NET APM Agent repo.

That'll fix the issue, but we also have to make sure that `Elastic.Apm.SerilogEnricher` forces users to use the latest agent, otherwise they'll run into the same bug.

So, once the next APM .NET Agent version is out which contains https://github.com/elastic/apm-agent-dotnet/pull/753, we need to update [Elastic.Apm.SerilogEnricher.csproj](https://github.com/elastic/ecs-dotnet/blob/master/src/Elastic.Apm.SerilogEnricher/Elastic.Apm.SerilogEnricher.csproj#L10) and make sure Elastic.Apm.SerilogEnricher depends on the version with the fix.

**Comment by codebrain** [comment]
Makes sense @gregkalapos , if you want to ping in here when it is ready I can handle the increment and publishing.

We have some releases in the pipeline for:

`1.4.3` - https://github.com/elastic/ecs-dotnet/pulls?q=is%3Apr+is%3Aopen+label%3Av1.4.3
`1.5.0` - https://github.com/elastic/ecs-dotnet/pulls?q=is%3Apr+is%3Aopen+label%3Av1.5.0

So will need to ensure this is coordinated properly.

**Comment by ffMathy** [comment]
I guess it is ready now right?

**Comment by gregkalapos** [comment]
Right, Elastic APM 1.4.0 is out which has the fix.
I opened #66.
