### ISSUE TITLE
[FEATURE] Change Elastic.CommonSchema.Client.Ip to string[] and store IPv4 and IPv6 values separately when pulled from HttpContext

### ISSUE THREAD

**Issue by olavaukan** [elastic/ecs-dotnet#64]
**Is your feature request related to a problem? Please describe.**
The ECS description for the Client.IP field seems to suggest that it supports multiple values: "Can be one or multiple IPv4 or IPv6 addresses." and is currently implemented as a string. When pulling data from HttpContext you end up with a value that contains both IPv4 and IPv6 addresses as a single string. It would be really useful to have these as separate values because with the current implementation it becomes harder to filter for a given IP-address when searching the logs.

**Describe the solution you'd like**
Change the Elastic.CommonSchema.Client.Ip datatype from string to string[] and change the two implementations of Elastic.CommonSchema.Serilog.HttpAdapter to get the IPv4 and IPv6 addresses separately. Maybe the MapToIPv4() and MapToIPv6() methiods are useful?
```
var ip4 = _httpContextAccessor.HttpContext.Features.Get<IHttpConnectionFeature>()?.RemoteIpAddress.MapToIPv4();
var ip6 = _httpContextAccessor.HttpContext.Features.Get<IHttpConnectionFeature>()?.RemoteIpAddress.MapToIPv6();
```

**Describe alternatives you've considered**
Perhaps a config option in Elastic.CommonSchema.Serilog.IEcsTextFormatterConfiguration where you can choose if you want to store the IPv4, IPv6 og both addresses in the Client.Ip field? Then you wouldn't have to change the datatype.

**Additional context**
This is what is currently logged for Client when writing a log event using Elastic.CommonSchema.Serilog.EcsTextFormatter:
```
    "client": {
        "user": {
            "id": ["de52e1bd-7486-45f6-bed0-3734f655f563"],
            "name": "administrator"
        },
        "address": "::ffff:172.19.0.1",
        "ip": "::ffff:172.19.0.1"
    }
```
It would be nize to instead get something like this:
```
    "client": {
        "user": {
            "id": ["de52e1bd-7486-45f6-bed0-3734f655f563"],
            "name": "administrator"
        },
        "address": "::ffff:172.19.0.1",
        "ip": ["::ffff","172.19.0.1"]
    }
```

**Comment by codebrain** [comment]
Hi @olavaukan 

You are correct, the generated .NET types in `1.4.0` are missing `string[]` for the following fields:

- `client.ip`
- `destination.ip`
- `server.ip`
- `source.ip`

ECS 1.5.0 sought to address this by introducing the `normalize->array` definitions in the YAML schema; https://github.com/elastic/ecs/releases/tag/v1.5.0.

I have checked the `1.5.0` YAML schema and it appears that sadly the above fields are missing the array definition too. I will open an issue on the elastic/ecs repo for this.

In the meantime I have fixed this on the upcoming `1.5.0` release PR here: https://github.com/elastic/ecs-dotnet/pull/60/commits/dc0d44fe1b0b3028a6a1cec044c7d8b30d4423a7

Let me see about getting this released in another patch release for the `1.4.0` schema.

Thanks again for you input, it is very much appreciated.

**Comment by olavaukan** [comment]
Sounds like 1.5.0 will resolve the type issue.

In the meantime I realized that the MapCustom method actually allows me to do all the changes I want in order to map things differently so there is no need for any other changes. For instance, this function will let me change the default mapping of Client.Ip to IPv4 so it matches my other log sources:

```
private static Base MapCustomClientIp(Base ecsEvent, IHttpContextAccessor httpAccessor)
{
    if (httpAccessor?.HttpContext == null)
        return ecsEvent;

    var ipAddress = httpAccessor.HttpContext.Features.Get<IHttpConnectionFeature>()?.RemoteIpAddress?.MapToIPv4().ToString();
    if (ecsEvent.Client != null && !string.IsNullOrEmpty(ipAddress))
        ecsEvent.Client.Ip = ipAddress;

    return ecsEvent;
}
```
Following the pattern from the ASP.NET Core with Serilog example I can then plug this into Program.cs like so:

```
// Override the Client.Ip mapping to extract only IPv4 address from HttpContext
formatterConfig.MapCustom((ecsEvent, logEvent) => MapCustomClientIp(ecsEvent, httpAccessor));

```
Thanks for the help!

**Comment by codebrain** [comment]
No worries, yes, the `MapCustom` is a handy function if you want to alter the event before it is serialised.
