### ISSUE TITLE
[FEATURE] .NET Core 2.1 Support for Serilog and NLog

### ISSUE THREAD

**Issue by Yukon** [elastic/ecs-dotnet#72]
**Is your feature request related to a problem? Please describe.**
I could not find any documentation as to why Serilog and NLog integration requires Http.Abstractions 2.2.0. The latest Serilog (2.9.0) still supports .NET Core 2.1 and seems unusual that the ECS requires 3.0.

**Describe the solution you'd like**
Target Microsoft.AspNetCore.Http.Abstractions 2.1.1 or greater instead of 2.2.0.

**Describe alternatives you've considered**
I have back-ported the Serilog package to use Http.Abstractions 2.1.1 with no issues from my initial testing.

**Additional context**
N/A

**Comment by snakefoot** [comment]
Created PR #76

**Comment by Yukon** [comment]
@Mpdreamz What is the schedule for releasing patch builds? Would like to use the official package with this fix.
